In [ ]:
import numpy as np
# 1D array in Cumu sum
array= np.array([1,3,6,8,9])
# axis is equal none by default in 1d arrays thats mean flattens
print("print.1 :",np.cumsum(array))


print.1 : [ 1  4 10 18 27]


In [ ]:
import numpy as np
# 2D array in Cumu sum
array= np.array([[1,3,6],[2,4,7],[1,1,1]])
# axis is equal none by default in 2d arrays , thats mean flattens first.
# 1- flatten the array first to be [1,3,6,2,4,7,1,1,1]
# 2- Cumulative Sum = [1,1+3.1+3+5,...,...]
print("print.2 :",np.cumsum(array))


# set value to axis 
# axis equal 0 means that start from first row to down and combine rows together >> top to bottom
print("print.3 :",np.cumsum(array,axis=0))

# axis equal 1 means that start from first column and combine columns together >> left to right
print("print.4 :",np.cumsum(array,axis=1))


print.2 : [ 1  4 10 12 16 23 24 25 26]
print.3 : [[ 1  3  6]
 [ 3  7 13]
 [ 4  8 14]]
print.3 : [[ 1  4 10]
 [ 2  6 13]
 [ 1  2  3]]


In [ ]:
import numpy as np
# 1D array in Cumu prod
array= np.array([1,3,6,8,9])
# axis is equal none by default in 1d arrays thats mean flattens
print("print.5 :",np.cumprod(array))


print.5 : [   1    3   18  144 1296]


In [15]:
import numpy as np
# 2D array in Cumu prod
array = np.array([[1,3,6],[2,4,7],[1,1,1]])
# axis is equal none by default in 2d arrays , thats mean flattens first.
# 1- flatten the array first to be [1,3,6,2,4,7,1,1,1]
# 2- Cumulative Prod = [1,1*3,1*3*6,...]
print("print.6 :", np.cumprod(array))

# axis equal 0 means top to bottom (combine rows)
print("print.7 :", np.cumprod(array, axis=0))

# axis equal 1 means left to right (combine columns)
print("print.8 :", np.cumprod(array, axis=1))


print.6 : [   1    3   18   36  144 1008 1008 1008 1008]
print.7 : [[ 1  3  6]
 [ 2 12 42]
 [ 2 12 42]]
print.8 : [[ 1  3 18]
 [ 2  8 56]
 [ 1  1  1]]
