In [8]:
import numpy as np

array = np.array([1, 3, 4, 5, 8, 12, 15, 55])
# save function saves the array in binary format with .npy extension by default
np.save("some_array", array)
# load the file using the full file name
print(np.load("some_array.npy"))

[ 1  3  4  5  8 12 15 55]


In [9]:
import numpy as np

array  = np.array([1, 3, 4, 5, 8, 12, 15, 55])
array2 = np.array([1, 2, 4, 8, 232, 11, 25, 99])

# ── Method 1: savez without names ──────────────────────────────────────────
# Arrays are auto-named arr_0, arr_1, arr_2, ...
np.savez("arrays.npz", array, array2)

arch = np.load("arrays.npz")
print(arch["arr_0"])   # first array
print(arch["arr_1"])   # second array

# ── Method 2: savez with keyword names (recommended) ───────────────────────
# Give each array a meaningful name using keyword arguments
np.savez("arrays_named.npz", first=array, second=array2)

arch_named = np.load("arrays_named.npz")
print(arch_named["first"])
print(arch_named["second"])

# You can also inspect all stored array names with:
print(arch_named.files)   # ['first', 'second']

# ── Method 3: savez_compressed ─────────────────────────────────────────────
# Same as savez but compresses the file — useful for large arrays
np.savez_compressed("arrays_compressed.npz", first=array, second=array2)

arch_compressed = np.load("arrays_compressed.npz")
print(arch_compressed["first"])

[ 1  3  4  5  8 12 15 55]
[  1   2   4   8 232  11  25  99]
[ 1  3  4  5  8 12 15 55]
[  1   2   4   8 232  11  25  99]
['first', 'second']
[ 1  3  4  5  8 12 15 55]
