In [ ]:
import numpy as np

arr1 = np.array([[2,12],[3,4]])
arr2 = np.array([[6,5],[7,10]])
# you can multiply arrays using one of these ways
print(arr1@arr2)
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))

['10' 'm']
[[ 96 130]
 [ 46  55]]
[[ 96 130]
 [ 46  55]]
[[ 96 130]
 [ 46  55]]
