In [1]:
import numpy as np

# ─────────────────────────────────────────────
# np.where — ALL common use cases
# Syntax: np.where(condition, x, y)
#   → where condition is True  → take from x
#   → where condition is False → take from y
# ─────────────────────────────────────────────

# 1. Basic: choose between two arrays
xarr    = np.array([10, 20, 30, 40, 50, 60])
yarr    = np.array([-10, -20, -30, -40, -50, -60])
condarr = np.array([True, False, True, False, True, False])

result = np.where(condarr, xarr, yarr)
print("1. Two arrays :", result)
# [ 10 -20  30 -40  50 -60]

# ─────────────────────────────────────────────
# 2. Scalar values instead of arrays
result2 = np.where(condarr, 1, 0)
print("2. Scalars    :", result2)
# [1 0 1 0 1 0]

# ─────────────────────────────────────────────
# 3. Condition built from a comparison (most common real-world use)
arr = np.array([5, 15, 3, 22, 8, 17])

result3 = np.where(arr > 10, arr, 0)   # keep values > 10, replace rest with 0
print("3. Comparison :", result3)
# [ 0 15  0 22  0 17]

# ─────────────────────────────────────────────
# 4. Replace values in-place style (clipping negatives)
arr2 = np.array([-3, 7, -1, 4, -9, 2])

result4 = np.where(arr2 < 0, 0, arr2)   # replace negatives with 0
print("4. Clip neg   :", result4)
# [0 7 0 4 0 2]

# ─────────────────────────────────────────────
# 5. With a 2-D array
matrix = np.array([[1, -2, 3],
                   [-4,  5, -6],
                   [7,  -8,  9]])

result5 = np.where(matrix > 0, matrix, 0)   # zero out negatives
print("5. 2-D array  :\n", result5)

# ─────────────────────────────────────────────
# 6. Nested np.where — multiple conditions (like if / elif / else)
scores = np.array([35, 55, 70, 85, 95])

grades = np.where(scores >= 90, 'A',
         np.where(scores >= 75, 'B',
         np.where(scores >= 60, 'C',
         np.where(scores >= 50, 'D', 'F'))))

print("6. Nested     :", grades)
# ['F' 'D' 'C' 'B' 'A']

# ─────────────────────────────────────────────
# 7. np.where with ONE argument → returns INDICES of True elements
arr3 = np.array([0, 5, 0, 3, 0, 8])

indices = np.where(arr3 != 0)          # returns a tuple of index arrays
print("7. Indices    :", indices)       # (array([1, 3, 5]),)
print("   Values     :", arr3[indices]) # [5 3 8]

# ─────────────────────────────────────────────
# 8. One-argument form on a 2-D array → row & col indices
mat2 = np.array([[0, 2], [3, 0], [0, 6]])
rows, cols = np.where(mat2 > 0)
print("8. 2-D rows   :", rows)          # [0 1 2]
print("   2-D cols   :", cols)          # [1 0 1]


1. Two arrays : [ 10 -20  30 -40  50 -60]
2. Scalars    : [1 0 1 0 1 0]
3. Comparison : [ 0 15  0 22  0 17]
4. Clip neg   : [0 7 0 4 0 2]
5. 2-D array  :
 [[1 0 3]
 [0 5 0]
 [7 0 9]]
6. Nested     : ['F' 'D' 'C' 'B' 'A']
7. Indices    : (array([1, 3, 5]),)
   Values     : [5 3 8]
8. 2-D rows   : [0 1 2]
   2-D cols   : [1 0 1]
